using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Onvif IP Camera Manager")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Ozeki Ltd.")]
[assembly: AssemblyProductAttribute("Onvif IP Camera Manager")]
[assembly: AssemblyCopyrightAttribute("Copyright © Ozeki Ltd. 2014")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("0DE3ABA2-8042-4DCD-B7B8-E12355984584")]
[assembly: AssemblyVersionAttribute("11.1.2.203")]

